### PR TITLE
Add more entries in sitemap.xml

### PR DESCRIPTION
**Pull request by azeey**
This also updates priorities.

### CODE REVIEW

**Comment by nkoenig** [comment]
Did you manually add some of these or use a script? There are a number of sitemap references to released versions, which implies that we would want to update this each release and for each EOL.

At a higher level, do you know if the release level of granularity is worth it? We could, for example, just include the `latest` links.

**Comment by azeey** [comment]
I generated this semi-automatically by tapping into the `doc` component and my hope is to somehow incorporate that into our deployment script, but I haven't figured that out yet. In the mean time, since a lot of the important pages are not currently indexed (according to the google search console), I thought I'd update the sitemap to remedy that.

> At a higher level, do you know if the release level of granularity is worth it? We could, for example, just include the latest links.

Good question. Since most of the content is unchanged between versions and the newer versions are usually a superset, I'd think getting those indexed would be sufficient. But by including the older versions in the sitemap with low priority, I was hoping the search engine would show preference to the latest versions and only show the older versions if the search query is a better match. Otherwise, if we left them out of the sitemap, those pages might get indexed, for e.g., if they get linked from somewhere else, and get a default priority of 0.5.  This is just a hunch based on what happens if you don't set the `priority` tag for a link. I don't know for sure if it works that way. So let me know if you'd prefer to only have the `latest` links.

**Comment by nkoenig** [comment]
Some form of automation would be nice, but not a reason to hold this up.

Will the google search console tell you how much gazebosim.org has improved when these changes are deployed?

**Review by nkoenig — APPROVED** [review]

**Comment by azeey** [comment]
> Will the google search console tell you how much gazebosim.org has improved when these changes are deployed?

I've added your account in case you're interested in looking at the data. I'm still learning how to use it, but the main thing I'm going for is to get all the pages indexed so that when searching for example "gazebo ubuntu", some of the pages from gazebosim.org/docs will show up. There's a URL inspection section that shows if a URL is indexed or not which is how I found out a lot of our docs pages are not currently indexed.

**Pull request merged**
